language: r
dist: bionic
cache: packages

r_github_packages:
  - richelbilderbeek/bbbq

r_packages:
  - beastier

install:
  # ImageMagick
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # csv2latex
  - sudo apt install csv2latex
  - sudo apt install r-cran-testthat r-cran-stringr r-cran-dplyr r-cran-readr r-cran-knitr

after_script:
  - make

