language: r
dist: bionic
cache: packages

r_packages:
  - beastier
  - dplyr
  - magrittr
  - readr
  - testthat

r_github_packages:
  - richelbilderbeek/bbbq

install:
  # ImageMagick
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # csv2latex
  - sudo apt install csv2latex

after_script:
  - make

