language: r
dist: bionic
cache: packages

r_github_packages:
  - jtextor/epitope-prediction
  - richelbilderbeek/mcbette
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette
  - richelbilderbeek/peregrine
  - richelbilderbeek/beastier
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/bbbq

before_install:
  # From https://stackoverflow.com/a/20042195
  - Rscript -e "update.packages(checkBuilt = TRUE, ask = FALSE)"
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
 
after_install:
  - sudo apt install r-cran-testthat r-cran-stringr r-cran-dplyr r-cran-readr r-cran-knitr r-cran-rcpp

after_script:
  - make use_test_proteomes_and_haplotypes
  - make peregrine
  - make figures
  - if [ ! -f fig_f_tmh_mhc2_grid.png ]; then echo "file 'fig_f_tmh_mhc2_grid.png' not found" ; exit 1 ; fi

